### ISSUE TITLE
Problem installing version 1.1.3

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-python#260]
### Because

Running `pip install clams-python=1.1.3` in a clean Python 3.10 based environment gives an error:

```
AttributeError: module 'setuptools.command' has no attribute 'sdist'
```

This seems to happen with at least a bunch of versions <3.1.2 (I also tried 1.1.6, 1.2.6 and 1.3.0 and 1.3.1).

Updating pip and setuptools did not work. The weird thing is that I do have a setup at work with clams-python==1.1.3 so at some point it worked (I will look at it when I am at work).

### Done when

Done when there is a workaround or we decide not to bother about older versions.

### Additional context

I was trying to do this to replicate an error reported in https://github.com/clamsproject/mmif-summarizer/issues/21

**Comment by keighrim** [comment]
this is because of changes in setuptools API. You have to install an old version of setuptools. Closing as resolved.
